@startmindmap

title "GCP"
footer Disponível em: https://github.com/acnaweb/gcp

*[#F8F8FF]  GCP

**[#LightGray] Zonas e Regiões
***_ Regions -> agrupamento lógico
***_ Zones -> Datacenters
***_ Network Edge Locations
***_ Regions contains 3 Zones 
***[#LightGray] Datacenters
****_ 100 kms between 

**[#LightGray] Services
***_ Compute Engine
***_ App Engine (servless)
***_ Cloud SQL
***_ Cloud CDN
***_ Cloud DNS

**[#LightGray] Free tier
***_ $ 300

**[#LightGray] Hierarchy
***_ $ Organization (Company) > Folders > Projects > Resources



@endmindmap